language: python
python:
#  - "3.3"
  - "2.7"
#  - "pypy"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - "pip install nibabel"
# command to run tests, e.g. python setup.py test
script: nosetests -v
